/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package simuladordebatalhapokemon;

import java.io.FileInputStream;
import static java.lang.Thread.sleep;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javazoom.jl.player.Player;

/**
 *
 * @author Pedro
 */
public class CampoBatalha extends javax.swing.JFrame {

    Pokemon squirtle = new Pokemon("Squirtle", "Água", 200, 7);
    Pokemon bulbasauro = new Pokemon("Bulbasauro", "Planta", 250, 5);
    Batalha batalha = new Batalha();


    public CampoBatalha() {
        initComponents();
        barraVida1.setValue(squirtle.getVida());
        barraVida2.setValue(bulbasauro.getVida());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pngSquirtle = new javax.swing.JLabel();
        pngBulbasauro = new javax.swing.JLabel();
        barraVida1 = new javax.swing.JProgressBar();
        barraVida2 = new javax.swing.JProgressBar();
        bAtaque = new javax.swing.JButton();
        fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        pngSquirtle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/simuladordebatalhapokemon/Squitle.png"))); // NOI18N
        jPanel1.add(pngSquirtle);
        pngSquirtle.setBounds(40, 630, 280, 300);

        pngBulbasauro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/simuladordebatalhapokemon/w82as-wjSgY-256s.png"))); // NOI18N
        jPanel1.add(pngBulbasauro);
        pngBulbasauro.setBounds(1060, 570, 270, 250);

        barraVida1.setForeground(new java.awt.Color(0, 204, 102));
        barraVida1.setMaximum(200);
        jPanel1.add(barraVida1);
        barraVida1.setBounds(90, 590, 220, 20);

        barraVida2.setForeground(new java.awt.Color(0, 204, 102));
        barraVida2.setMaximum(250);
        jPanel1.add(barraVida2);
        barraVida2.setBounds(1070, 530, 220, 20);

        bAtaque.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bAtaque.setText("Ataque!");
        bAtaque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAtaqueActionPerformed(evt);
            }
        });
        jPanel1.add(bAtaque);
        bAtaque.setBounds(310, 940, 100, 50);

        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/simuladordebatalhapokemon/CampoBatalha.jpg"))); // NOI18N
        jPanel1.add(fundo);
        fundo.setBounds(0, 0, 1371, 1110);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1370, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1109, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bAtaqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAtaqueActionPerformed

        barraVida2.setValue(barraVida2.getValue() - batalha.causarDano(squirtle));
        JOptionPane.showMessageDialog(null, "Squirtle causou: " + batalha.causarDano(squirtle) + " de dano!");
        if (barraVida2.getValue() <= 0) {
            JOptionPane.showMessageDialog(null, "Squirtle ganhou!!!");
            dispose();
            System.exit(0);
        }

        barraVida1.setValue(barraVida1.getValue() - batalha.causarDano(bulbasauro));
        if (barraVida1.getValue() <= 0) {
            JOptionPane.showMessageDialog(null, "Bulbasauro ganhou!!!");
            dispose();
            System.exit(0);
        }
        JOptionPane.showMessageDialog(null, "Bulbasauro causou: " + batalha.causarDano(bulbasauro) + " de dano!");


    }//GEN-LAST:event_bAtaqueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CampoBatalha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CampoBatalha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CampoBatalha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CampoBatalha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CampoBatalha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAtaque;
    private javax.swing.JProgressBar barraVida1;
    private javax.swing.JProgressBar barraVida2;
    private javax.swing.JLabel fundo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel pngBulbasauro;
    private javax.swing.JLabel pngSquirtle;
    // End of variables declaration//GEN-END:variables
}
